config:
  target: 'http://shop.dev/api'
  phases:
    - duration: 10
      arrivalRate: 30
  processor: './plugin-random-ip.js'

scenarios:
  - name: 'Products test scenario 1'
    flow:
      - post:
          beforeRequest: setIP
          url: '/users/signin'
          json:
            email: 'test@test.com'
            password: 'test'
      - post:
          headers:
            X-Forwarded-For: '{{ipAddress}}'
          url: '/products'
          json:
            title: 'Test Product'
            price: 10
            description: 'Lorem ipsum'
          capture:
            json: '$.id'
            as: 'productId'
      - get:
          headers:
            X-Forwarded-For: '{{ipAddress}}'
          url: '/products/{{productId}}'
      - put:
          headers:
            X-Forwarded-For: '{{ipAddress}}'
          url: '/products/{{productId}}'
          json:
            title: 'New Title'
            price: 20
            description: 'New description'
          afterResponse: logIP
