apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }

    http {
      log_format upstream '$remote_addr - $upstream_addr - [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';
      access_log /var/log/nginx/access.logs upstream;

      set_real_ip_from 0.0.0.0/0;
      real_ip_header x-original-forwarded-for;

      upstream products {
        ip_hash;
        server 10.1.6.202:3000;
        server 10.1.6.206:3000;
        server 10.1.6.204:3000;
      }

      server {
        listen 80;

        location / {
          add_header X-Backend-Server $upstream_addr;
          proxy_pass http://products;
        }
      }
    }
