apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }

    http {
      set_real_ip_from 0.0.0.0/0;
      real_ip_header x-original-forwarded-for;

      upstream products {
        ip_hash;
        server 10.1.5.179:3000;
        server 10.1.5.181:3000;
        server 10.1.5.182:3000;
      }

      server {
        listen 80;

        location / {
          add_header X-Backend-Server $upstream_addr;
          proxy_pass http://products;
        }
      }
    }
